#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable clamav-milter.service

  if test -f "disabled.bin"; then
    echo "antivirus is already disabled."
  else
    touch "disabled.bin"
    if systemctl is-active --quiet clamav-milter-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop clamav-milter.service
    else
      echo "antivirus will be disabled on next reboot."
    fi
  fi

fi


