#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable clamav-milter.service

  if test ! -f "disabled.bin"; then
    echo "antivirus is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet clamav-milter-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart clamav-milter-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart clamav-milter.service
    else
      echo "antivirus will be enabled on next reboot."
    fi
  fi

fi

